/* Foodle word data — food words with emoji + flavor copy for the win card. */

const FOODLE_WORDS = {
  5: [
    { w: "APPLE", e: "🍎", o: "Worldwide", d: "The orchard's quiet ambassador. Crisp, tart, sweet — the original snack." },
    { w: "BREAD", e: "🍞", o: "Mesopotamia", d: "Flour, water, salt, time. Civilization's first comfort food." },
    { w: "PIZZA", e: "🍕", o: "Naples, Italy", d: "A flatbread, a canvas, a global obsession. Naples started it in 1889." },
    { w: "SALAD", e: "🥗", o: "Ancient Rome", d: "From Latin 'sal' — salt. The Romans dressed greens in brine and oil." },
    { w: "MANGO", e: "🥭", o: "South Asia", d: "The 'king of fruits' — cultivated in India for over 4,000 years." },
    { w: "MELON", e: "🍈", o: "Africa / Persia", d: "Summer's sweetness in a heavy rind. Watermelon, cantaloupe, honeydew." },
    { w: "GRAPE", e: "🍇", o: "Near East", d: "Ferment it and you have civilization's other obsession." },
    { w: "PEACH", e: "🍑", o: "China", d: "Symbol of immortality in Chinese tradition; fuzz on the outside, gold within." },
    { w: "LEMON", e: "🍋", o: "Northeast India", d: "Sour, fragrant, indispensable. A drop wakes any dish up." },
    { w: "OLIVE", e: "🫒", o: "Mediterranean", d: "Cured, pressed, or whole — the Mediterranean's quiet workhorse." },
    { w: "ONION", e: "🧅", o: "Central Asia", d: "Layered, unassuming, makes you cry — the foundation of every cuisine." },
    { w: "BACON", e: "🥓", o: "Roman / Saxon", d: "Cured pork belly. The reason vegetarianism is hard." },
    { w: "CURRY", e: "🍛", o: "Indian subcontinent", d: "A whole spice cabinet, simmered. Every region has its own." },
    { w: "TACOS", e: "🌮", o: "Mexico", d: "Tortilla, filling, salsa. Honest, portable, perfect." },
    { w: "SUSHI", e: "🍣", o: "Japan", d: "Vinegared rice and fish. Started as a preservation method, became an art." },
    { w: "BAGEL", e: "🥯", o: "Poland", d: "Boiled then baked. Polish-Jewish ingenuity, perfected in New York." },
    { w: "CANDY", e: "🍬", o: "Persia / India", d: "Crystallized sugar — once medicine, now mostly mischief." },
    { w: "SUGAR", e: "🍚", o: "New Guinea", d: "Sugarcane traveled from the Pacific to remake the world's palate." },
    { w: "FLOUR", e: "🌾", o: "Worldwide", d: "Ground grain. The first ingredient in nearly every comfort food." },
    { w: "CREAM", e: "🥛", o: "Worldwide", d: "Milk's rich top layer. Whipped, soured, churned, or simply poured." },
    { w: "RAMEN", e: "🍜", o: "Japan (via China)", d: "Wheat noodles, deeply flavored broth. A 12-hour stock in a bowl." },
    { w: "PASTA", e: "🍝", o: "Italy", d: "Over 350 named shapes. Each one is engineered for a specific sauce." },
    { w: "HONEY", e: "🍯", o: "Worldwide", d: "Bees reduce nectar to syrup. The original sweetener." },
    { w: "CHILI", e: "🌶️", o: "Mexico (peppers); Texas (stew)", d: "From the Aztec 'chīlli'. Heat, fruit, and depth in one pod." },
    { w: "BEANS", e: "🫘", o: "Americas", d: "Fiber, protein, patience. The slow-cooked backbone of dozens of cuisines." },
    { w: "BERRY", e: "🫐", o: "Worldwide", d: "Strawberry, blueberry, raspberry — small fruit, big flavor." },
    { w: "COCOA", e: "🍫", o: "Mesoamerica", d: "The Aztecs drank it bitter and spiced. We added milk and sugar later." },
    { w: "DONUT", e: "🍩", o: "Netherlands → USA", d: "Fried dough with a hole. Glazed, frosted, filled, or plain." },
    { w: "FUDGE", e: "🍫", o: "USA, late 1800s", d: "A 'fudged' batch of caramel that turned out better than the original." },
    { w: "GRAVY", e: "🥣", o: "Worldwide", d: "Pan drippings + flour + stock. The most rewarding side effect of roasting." },
    { w: "JELLY", e: "🍇", o: "Worldwide", d: "Fruit + sugar + pectin. Wobbly, jewel-toned, eternally on toast." },
    { w: "MOCHA", e: "☕", o: "Yemen", d: "Named for the port city of Mokha — coffee meets chocolate." },
    { w: "NACHO", e: "🧀", o: "Piedras Negras, 1943", d: "Invented in 30 seconds by a maître d' named Ignacio. Hence: nacho." },
    { w: "PECAN", e: "🌰", o: "Southern USA", d: "A native American nut, buttery and rich. The pie was inevitable." },
    { w: "STEAK", e: "🥩", o: "Scandinavia (the word)", d: "From Old Norse 'steik'. A cut of meat, seared hot and fast." },
    { w: "SYRUP", e: "🍁", o: "Indigenous N. America", d: "Tap a maple in late winter; boil 40 gallons down to 1." },
    { w: "TOAST", e: "🍞", o: "Roman times", d: "Bread, browned. Also the act of raising a glass — same Latin root." },
    { w: "WAFER", e: "🍪", o: "Medieval Europe", d: "Thin, crisp, often religious. The cookie's elegant cousin." },
    { w: "WHEAT", e: "🌾", o: "Fertile Crescent", d: "Domesticated 10,000 years ago. Without it, no bread, pasta, or beer." },
    { w: "YEAST", e: "🍞", o: "Worldwide", d: "A single-celled fungus that ferments. We owe it bread, beer, and wine." },
    { w: "BROTH", e: "🥣", o: "Worldwide", d: "Bones, water, time, salt. The simplest soup is often the best." },
    { w: "CIDER", e: "🍎", o: "Pre-Roman Europe", d: "Fermented apple juice. Older than most beer styles." },
    { w: "CRUST", e: "🥧", o: "Worldwide", d: "The browned, structural perimeter — of bread, pie, pizza." },
    { w: "DATES", e: "🌴", o: "Middle East", d: "The desert's caramel. Cultivated for at least 6,000 years." },
    { w: "FRIES", e: "🍟", o: "Belgium / France", d: "Both countries claim them. We just keep eating them." },
    { w: "GRAIN", e: "🌾", o: "Worldwide", d: "Edible seeds of grasses. The staple foods of every civilization." },
    { w: "KEBAB", e: "🍢", o: "Middle East", d: "Skewered meat, grilled over fire. The world's oldest fast food." },
    { w: "LATTE", e: "☕", o: "Italy", d: "Espresso + steamed milk. Italian for 'milk' — order carefully there." },
    { w: "MAPLE", e: "🍁", o: "North America", d: "The tree, the leaf, the syrup. Canada's edible icon." },
    { w: "PESTO", e: "🌿", o: "Genoa, Italy", d: "Basil, pine nuts, garlic, oil, parmesan — pounded in a mortar." },
    { w: "PRUNE", e: "🍑", o: "Western Asia", d: "A dried plum. Concentrated sweetness, a baker's secret weapon." },
    { w: "ROAST", e: "🍖", o: "Worldwide", d: "Dry heat, time, browning. The Maillard reaction is the whole show." },
    { w: "SCONE", e: "🥐", o: "Scotland", d: "Quick bread, slightly sweet. Devonshire cream is non-negotiable." },
    { w: "SPICE", e: "🧂", o: "Worldwide", d: "Bark, seed, bud, root. They redrew maps and started wars." },
    { w: "THYME", e: "🌿", o: "Mediterranean", d: "Earthy, lemony, indispensable in stews. Pairs with everything." },
    { w: "WINGS", e: "🍗", o: "Buffalo, NY, 1964", d: "Anchor Bar, late-night kitchen, leftover chicken wings — history." },
  ],

  6: [
    { w: "BANANA", e: "🍌", o: "SE Asia", d: "A berry, technically. The Cavendish makes up almost every banana you've eaten." },
    { w: "CARROT", e: "🥕", o: "Persia", d: "Originally purple. Dutch growers bred the orange version in the 1600s." },
    { w: "COOKIE", e: "🍪", o: "Persia / Netherlands", d: "From Dutch 'koekje' — little cake. Test of any oven." },
    { w: "CHEESE", e: "🧀", o: "Worldwide", d: "Curdled milk, aged with intention. Over 1,800 named varieties." },
    { w: "COFFEE", e: "☕", o: "Ethiopia", d: "A goat herder noticed his goats were extra peppy. The rest is history." },
    { w: "MUFFIN", e: "🧁", o: "Britain (English) / USA (American)", d: "Two unrelated foods, same name. The American one is basically cake." },
    { w: "ORANGE", e: "🍊", o: "China", d: "The fruit named the color. Before that, English called it 'yellow-red'." },
    { w: "POTATO", e: "🥔", o: "Andes", d: "Domesticated 7,000+ years ago. Reshaped European diets after 1500." },
    { w: "TOMATO", e: "🍅", o: "Andes", d: "A fruit pretending to be a vegetable. Ruled illegal in 1893." },
    { w: "WALNUT", e: "🌰", o: "Persia", d: "Brain-shaped, brain-healthy. Romans called it 'Jupiter's acorn'." },
    { w: "YOGURT", e: "🥛", o: "Mesopotamia / Central Asia", d: "Fermented milk. Older than written history; healthier than most things." },
    { w: "CASHEW", e: "🥜", o: "Brazil", d: "Each cashew grows from a fruit, the cashew apple. The nut is the seed." },
    { w: "GINGER", e: "🫚", o: "SE Asia", d: "A rhizome, not a root. Warming, pungent, indispensable." },
    { w: "SHRIMP", e: "🦐", o: "Worldwide", d: "Cooks in 90 seconds. Don't overdo it." },
    { w: "BUTTER", e: "🧈", o: "Worldwide", d: "Cream, agitated until the fat separates. The point of life." },
    { w: "GARLIC", e: "🧄", o: "Central Asia", d: "Anti-vampire, anti-bland. A culinary cure-all." },
    { w: "SALMON", e: "🐟", o: "N. Atlantic / Pacific", d: "Pink-fleshed from a krill diet. Smoked, grilled, raw — always good." },
    { w: "TURKEY", e: "🦃", o: "North America", d: "Domesticated by the Aztecs. The bird is named after the country, sort of." },
    { w: "CELERY", e: "🥬", o: "Mediterranean", d: "Mostly water, mostly underrated. The crunch in every mirepoix." },
    { w: "PEPPER", e: "🌶️", o: "India (black) / Americas (chili)", d: "Two unrelated plants, one universal pantry word." },
    { w: "PICKLE", e: "🥒", o: "Mesopotamia", d: "Salt, vinegar, time. The original fridge." },
    { w: "RADISH", e: "🌶️", o: "SE Asia", d: "Peppery, crisp, cheerful. Eat them with butter and salt." },
    { w: "SESAME", e: "🌱", o: "Africa / India", d: "One of the oldest oilseed crops, cultivated for over 3,000 years." },
    { w: "TURNIP", e: "🥬", o: "Europe / Asia", d: "Before potatoes arrived, this was the staple root in Europe." },
    { w: "WAFFLE", e: "🧇", o: "Belgium", d: "Yeast-raised, deep grids made for catching syrup." },
    { w: "GELATO", e: "🍨", o: "Italy", d: "Less air, less fat, more flavor than ice cream. Served slightly warmer." },
    { w: "NUTMEG", e: "🌰", o: "Banda Islands", d: "A spice so valuable the Dutch traded Manhattan for the island that grew it." },
    { w: "QUICHE", e: "🥧", o: "Lorraine, France", d: "Eggs, cream, pastry. A French formality that's surprisingly forgiving." },
    { w: "QUINOA", e: "🌾", o: "Andes", d: "A 'pseudocereal' — actually a seed. The Inca called it the mother grain." },
    { w: "RAISIN", e: "🍇", o: "Worldwide", d: "A grape that traded juice for chew. Concentrated sun." },
    { w: "FENNEL", e: "🌿", o: "Mediterranean", d: "Bulb, fronds, seeds — every part is useful. Anise without the candy." },
    { w: "LENTIL", e: "🫘", o: "Near East", d: "Among the first plants ever farmed. Cooks in 20 minutes flat." },
    { w: "SORBET", e: "🍧", o: "Persia / Italy", d: "Frozen fruit, no dairy. Originally chilled with mountain snow." },
    { w: "ENDIVE", e: "🥬", o: "Belgium / Mediterranean", d: "Bitter, pale, elegant. Grown in the dark to keep it tender." },
    { w: "TOFFEE", e: "🍬", o: "Britain", d: "Butter and sugar, cooked dark. The grown-up cousin of caramel." },
    { w: "FONDUE", e: "🧀", o: "Switzerland", d: "Melted cheese, white wine, garlic, bread. Dinner as group activity." },
    { w: "KIMCHI", e: "🌶️", o: "Korea", d: "Salted, fermented, fiery cabbage. Korea has hundreds of regional versions." },
    { w: "ECLAIR", e: "🍰", o: "France", d: "Choux pastry, cream, chocolate glaze. French for 'flash of lightning'." },
    { w: "CEREAL", e: "🥣", o: "USA, 19th c.", d: "Cold breakfast in a box — a Battle Creek health-food invention." },
    { w: "DAIKON", e: "🥬", o: "East Asia", d: "A mild giant radish. Pickled, grated, simmered — endlessly versatile." },
    { w: "HUMMUS", e: "🥙", o: "Levant", d: "Chickpeas, tahini, lemon, garlic. A 13th-century recipe still in heavy rotation." },
    { w: "MATCHA", e: "🍵", o: "Japan", d: "Stone-ground green tea leaves. Whisked, not steeped." },
    { w: "MUSSEL", e: "🐚", o: "Worldwide coasts", d: "Steam open with white wine, garlic, parsley. Twelve minutes, total." },
    { w: "OYSTER", e: "🦪", o: "Worldwide coasts", d: "Eat them raw, with lemon. Each one tastes of its specific water." },
    { w: "PRAWNS", e: "🦐", o: "Worldwide", d: "Bigger than shrimp, mostly. A 'crawn' is not a thing — sorry." },
    { w: "SCAMPI", e: "🍤", o: "Italy", d: "Originally a small lobster. In America: shrimp in garlic butter and wine." },
    { w: "WASABI", e: "🌶️", o: "Japan", d: "True wasabi is rare. What you usually get is dyed horseradish." },
    { w: "PEANUT", e: "🥜", o: "South America", d: "Not a nut — a legume. Most are now grown in China and India." },
    { w: "ALMOND", e: "🌰", o: "Middle East", d: "California now grows 80% of the world's almonds." },
    { w: "GARLIC", e: "🧄", o: "Central Asia", d: "Anti-vampire, anti-bland. A culinary cure-all." },
  ],

  7: [
    { w: "AVOCADO", e: "🥑", o: "Mexico", d: "From Nahuatl 'āhuacatl'. A buttery fruit pretending to be a vegetable." },
    { w: "COCONUT", e: "🥥", o: "SE Asia / Pacific", d: "Drupe, not nut. Provides water, milk, oil, sugar, and a useful shell." },
    { w: "CABBAGE", e: "🥬", o: "Europe", d: "Wild Brassica oleracea also gave us broccoli, kale, and Brussels sprouts." },
    { w: "CHICKEN", e: "🍗", o: "SE Asia", d: "Domesticated from the red junglefowl 8,000+ years ago." },
    { w: "POPCORN", e: "🍿", o: "Mesoamerica", d: "Specific corn varieties whose kernels explode at 180°C. Magic, basically." },
    { w: "PRETZEL", e: "🥨", o: "Southern Germany", d: "Boiled in lye, then baked. The shape mimics arms folded in prayer." },
    { w: "SARDINE", e: "🐟", o: "Sardinia (the name)", d: "Tinned in oil, on toast, with lemon. The most underrated fish." },
    { w: "CRUMPET", e: "🥞", o: "Britain", d: "Yeasty, holey, griddled. Made for absorbing butter." },
    { w: "CUSTARD", e: "🍮", o: "Medieval Europe", d: "Eggs + dairy + heat. Stop just before it scrambles." },
    { w: "GRANOLA", e: "🥣", o: "USA, 1894", d: "Born as a health food — oats, sweetener, fat, baked crisp." },
    { w: "KETCHUP", e: "🍅", o: "China / SE Asia", d: "Originally a fermented fish sauce. Tomatoes joined the party in the 1800s." },
    { w: "LASAGNA", e: "🍝", o: "Italy", d: "Layers of pasta, ragù, béchamel, cheese. A weekend project worth doing." },
    { w: "MUSTARD", e: "🌭", o: "Eurasia", d: "Crushed seeds + acid. From Dijon's wine vinegar to American yellow." },
    { w: "OATMEAL", e: "🥣", o: "Scotland", d: "Hot cooked oats. Adaptable, frugal, the original power breakfast." },
    { w: "PANCAKE", e: "🥞", o: "Worldwide", d: "Every culture has one. Crepes, dosas, blini, hotcakes — all kin." },
    { w: "PUDDING", e: "🍮", o: "Britain", d: "In the UK, dessert. Elsewhere, specifically a creamy one. Sometimes savory." },
    { w: "RHUBARB", e: "🌿", o: "Asia", d: "Tart red stalks (leaves are toxic). Pie filler par excellence." },
    { w: "SPINACH", e: "🥬", o: "Persia", d: "Iron-rich (just not as much as Popeye claimed). Wilts in seconds." },
    { w: "VANILLA", e: "🌸", o: "Mexico", d: "From an orchid — the world's second-most expensive spice after saffron." },
    { w: "GOULASH", e: "🥘", o: "Hungary", d: "Beef, paprika, slow time. A herdsmen's stew turned national dish." },
    { w: "PAPRIKA", e: "🌶️", o: "Hungary / Spain", d: "Dried, ground sweet peppers. Sweet, smoked, or hot — pick your color." },
    { w: "POLENTA", e: "🌽", o: "Northern Italy", d: "Cornmeal, slowly stirred into creamy submission. Or fried into wedges." },
    { w: "PUMPKIN", e: "🎃", o: "North America", d: "A squash that became a holiday. Native to the Americas." },
    { w: "RAVIOLI", e: "🥟", o: "Italy", d: "Pasta dumplings, every region with its own filling." },
    { w: "SAUSAGE", e: "🌭", o: "Worldwide", d: "Ground meat in casing. Older than recorded cooking, basically." },
    { w: "HARISSA", e: "🌶️", o: "Tunisia", d: "Roasted chilies, garlic, caraway, oil. Stir into anything for instant depth." },
    { w: "CHOWDER", e: "🍲", o: "New England / France", d: "Creamy seafood soup. Clam, corn, fish — all welcome." },
    { w: "CHURROS", e: "🍩", o: "Spain / Portugal", d: "Star-tipped fried dough, dipped in thick chocolate. Breakfast, sometimes." },
    { w: "ANCHOVY", e: "🐟", o: "Mediterranean", d: "Salt-cured tiny fish. Melts into sauces and disappears, leaving deep umami." },
    { w: "APRICOT", e: "🍑", o: "Central Asia", d: "Fuzzy, golden, fleeting. A short summer fruit with an outsized flavor." },
    { w: "BISCUIT", e: "🥐", o: "UK / US", d: "Two countries, two foods. American: flaky and savory. British: a cookie." },
    { w: "BURRITO", e: "🌯", o: "Northern Mexico", d: "Flour tortilla, fully wrapped. Spanish for 'little donkey' — origin disputed." },
    { w: "CASSAVA", e: "🌱", o: "South America", d: "Starchy root. Tapioca, fufu, garri — feeds half a billion people." },
    { w: "CHEDDAR", e: "🧀", o: "Cheddar, England", d: "The world's most-eaten cheese. Mild, sharp, or extra-extra-sharp." },
    { w: "CRACKER", e: "🍘", o: "Worldwide", d: "Dry, thin, crisp baked dough. The vehicle for every cheese plate." },
    { w: "CUPCAKE", e: "🧁", o: "USA, 19th c.", d: "Originally measured in cups (hence the name). Now the perfect single serving." },
    { w: "EGGROLL", e: "🥟", o: "Chinese-American", d: "Crispy fried wrapper, cabbage and pork inside. American invention, broadly." },
    { w: "JASMINE", e: "🍚", o: "Thailand", d: "Long-grain rice with a faint floral aroma. The default Thai grain." },
    { w: "KUMQUAT", e: "🍊", o: "South China", d: "Pop the whole tiny citrus in your mouth — the peel is the sweet part." },
    { w: "MARMITE", e: "🍞", o: "Britain", d: "Concentrated yeast extract, brown and fierce. You love it or you don't." },
    { w: "PARSNIP", e: "🥕", o: "Eurasia", d: "Carrot's pale, sweet, earthy cousin. Roast it; nothing else." },
    { w: "SCALLOP", e: "🐚", o: "Worldwide coasts", d: "Sweet, dense bivalve. Sear hot for 90 seconds per side. Don't move them." },
    { w: "SHALLOT", e: "🧅", o: "Central Asia", d: "Subtler than onion, more refined than garlic. A French mainstay." },
    { w: "TILAPIA", e: "🐟", o: "Africa", d: "Mild, white, farmed everywhere. Older than Egyptian civilization." },
    { w: "ABALONE", e: "🐚", o: "Worldwide coasts", d: "A sea snail prized in East Asian cuisine. Tender if you treat it gently." },
    { w: "BOLOGNA", e: "🍖", o: "Bologna, Italy", d: "Mortadella's American cousin. Flatter, milder, the lunchbox classic." },
    { w: "CALZONE", e: "🥟", o: "Naples, Italy", d: "A folded-over pizza. Italian for 'trouser leg' — make of that what you will." },
    { w: "TANGELO", e: "🍊", o: "Hybrid (USA, 1900s)", d: "Tangerine × pomelo. Loose-skinned, juicy, bright." },
    { w: "BOURBON", e: "🥃", o: "Kentucky, USA", d: "Corn-based whiskey, charred oak barrels. Sweet, smoky, American." },
    { w: "CHAYOTE", e: "🥒", o: "Mesoamerica", d: "Pale-green squash, mild and crisp. Eat it raw or stewed." },
    { w: "TANDOOR", e: "🔥", o: "South / West Asia", d: "Clay oven, blistering heat. Where naan meets fire." },
  ],
};

const FOODLE_VALID = (() => {
  // valid guesses = answers + a small extra dictionary of common english 5/6/7-letter words
  // (small enough to ship inline; gameplay tolerates loose validation)
  const extras5 = "ABOUT,ABOVE,AFTER,AGAIN,ALONG,ANGLE,APART,ARENA,ARGUE,ARROW,ASIDE,AVOID,AWARD,AWARE,BAKER,BASIC,BEACH,BEGIN,BELOW,BIRTH,BLACK,BLAME,BLANK,BLAST,BLIND,BLOCK,BLOOM,BLOWN,BOARD,BOOST,BORED,BRAIN,BRAND,BRAVE,BREAK,BRICK,BRIEF,BRING,BROAD,BROWN,BUILD,CABLE,CAMEL,CARGO,CARRY,CATCH,CAUSE,CHAIN,CHAIR,CHASE,CHEAP,CHECK,CHESS,CHEST,CHIEF,CHILD,CHOKE,CHOSE,CIVIC,CIVIL,CLAIM,CLASS,CLEAN,CLEAR,CLERK,CLICK,CLIFF,CLIMB,CLOCK,CLOSE,CLOUD,COACH,COAST,COULD,COUNT,COURT,COVER,CRACK,CRAFT,CRASH,CRAZY,CROSS,CROWD,CROWN,CRUDE,DAILY,DEALT,DEPTH,DOZEN,DRAFT,DRAMA,DRANK,DRAWN,DREAM,DRESS,DRIED,DRILL,DRINK,DRIVE,DROVE,EARLY,EARTH,ELITE,EMPTY,ENEMY,ENJOY,ENTER,ENTRY,EQUAL,ERROR,EVENT,EVERY,EXACT,EXIST,EXTRA,FAITH,FALSE,FAULT,FENCE,FEWER,FIBER,FIELD,FIFTH,FIFTY,FIGHT,FINAL,FIRST,FIXED,FLAME,FLASH,FLEET,FLOOR,FLUID,FOCUS,FORCE,FORTH,FORTY,FORUM,FOUND,FRAME,FRANK,FRAUD,FRESH,FRONT,FROST,FROZE,FRUIT,FULLY,FUNNY,GIANT,GIVEN,GLASS,GLOBE,GLORY,GRAND,GRANT,GRASS,GREAT,GREEN,GROSS,GROUP,GROWN,GUARD,GUESS,GUEST,GUIDE,HAPPY,HARSH,HEART,HEAVY,HENCE,HOTEL,HOUSE,HUMAN,HUMOR,IDEAL,IMAGE,INDEX,INNER,INPUT,IVORY,JOINT,JUDGE,KNIFE,KNOCK,KNOWN,LABEL,LARGE,LASER,LATER,LAUGH,LAYER,LEARN,LEAST,LEAVE,LEGAL,LEVEL,LIGHT,LIMIT,LOCAL,LOOSE,LOWER,LOYAL,LUCKY,LUNCH,LYING,MAGIC,MAJOR,MARCH,MATCH,MAYBE,MAYOR,MEDIA,MERIT,METAL,METER,MIGHT,MINOR,MIXED,MODEL,MONEY,MONTH,MORAL,MOTOR,MOUNT,MOUSE,MOUTH,MOVIE,MUSIC,NAIVE,NEEDS,NEVER,NEWLY,NIGHT,NOBLE,NOISE,NORTH,NOVEL,NURSE,OCCUR,OCEAN,OFFER,OFTEN,ORDER,OTHER,OUGHT,OUNCE,OUTER,OWING,PAINT,PANEL,PAPER,PARTY,PEACE,PHASE,PHONE,PHOTO,PIECE,PILOT,PITCH,PLACE,PLAIN,PLANE,PLANT,PLATE,POINT,POUND,POWER,PRESS,PRICE,PRIDE,PRIME,PRINT,PRIOR,PROOF,PROUD,PROVE,QUEEN,QUEST,QUICK,QUIET,QUITE,RADIO,RAISE,RANGE,RAPID,RATIO,REACH,READY,REALM,REFER,RIGHT,RIVAL,RIVER,ROBOT,ROUGH,ROUND,ROUTE,ROYAL,RURAL,SCALE,SCENE,SCOPE,SCORE,SENSE,SERVE,SEVEN,SHALL,SHAPE,SHARE,SHARP,SHEEP,SHEET,SHELF,SHELL,SHIFT,SHINE,SHIRT,SHOCK,SHOOT,SHORT,SHOWN,SIGHT,SILLY,SINCE,SIXTH,SIXTY,SIZED,SKILL,SLEEP,SLIDE,SMALL,SMART,SMILE,SMOKE,SNAKE,SOLID,SOLVE,SORRY,SOUND,SOUTH,SPACE,SPARE,SPEAK,SPEED,SPELL,SPEND,SPENT,SPICE,SPILL,SPLIT,SPOKE,SPORT,STAFF,STAGE,STAKE,STAND,START,STATE,STEAM,STEEL,STEEP,STEER,STICK,STILL,STOCK,STONE,STOOD,STORE,STORM,STORY,STRIP,STUCK,STUDY,STUFF,STYLE,SUITE,SUPER,SWEET,SWIFT,SWING,SWORN,TABLE,TAKEN,TASTE,TAUGHT,TEACH,THANK,THEFT,THEIR,THEME,THERE,THESE,THICK,THING,THINK,THIRD,THOSE,THREE,THREW,THROW,TIGHT,TIRED,TITLE,TODAY,TOPIC,TOTAL,TOUCH,TOUGH,TOWER,TRACK,TRADE,TRAIN,TREAT,TREND,TRIAL,TRICK,TRIED,TRULY,TRUNK,TRUST,TRUTH,TWICE,UNDER,UNDUE,UNION,UNITY,UNTIL,UPPER,UPSET,URBAN,USAGE,USUAL,VALID,VALUE,VIDEO,VIRUS,VISIT,VITAL,VOCAL,VOICE,WASTE,WATCH,WATER,WHEEL,WHERE,WHICH,WHILE,WHITE,WHOLE,WHOSE,WOMAN,WOMEN,WORLD,WORRY,WORSE,WORST,WORTH,WOULD,WRITE,WRONG,WROTE,YIELD,YOUNG,YOUTH";
  const extras6 = "ACCEPT,ACCESS,ACROSS,ACTION,ACTIVE,ACTUAL,ADJUST,ADMIRE,ADVICE,ADVISE,AFFAIR,AFFECT,AFFORD,AFRAID,AGENCY,AGENDA,ALMOST,ALWAYS,AMOUNT,ANIMAL,ANNUAL,ANSWER,ANYONE,ANYWAY,APPEAL,APPEAR,AROUND,ARRIVE,ARTIST,ASLEEP,ASPECT,ASSESS,ASSIST,ASSUME,ATTACK,ATTEND,AUGUST,AUTHOR,AVENUE,BARELY,BARREL,BATTLE,BEAUTY,BECAME,BEFORE,BEHALF,BEHAVE,BEHIND,BELIEF,BELONG,BERLIN,BETTER,BEYOND,BIGGER,BISHOP,BORDER,BOTTLE,BOTTOM,BOUGHT,BRANCH,BREATH,BREEZE,BRIDGE,BRIGHT,BROKEN,BUDGET,BUREAU,CAMERA,CANCEL,CANCER,CANNON,CANNOT,CARBON,CAREER,CASTLE,CASUAL,CAUGHT,CENTER,CHANCE,CHANGE,CHARGE,CHOICE,CHOOSE,CHOSEN,CHURCH,CIRCLE,CLIENT,CLOSED,CLOSER,COFFEE,COLUMN,COMBAT,COMING,COMMIT,COMMON,COOLER,COPPER,CORNER,COSTLY,COUNTY,COUPLE,COURSE,COWARD,CREATE,CREDIT,CRISIS,CRITIC,CROWD,CRUISE,CUSTOM,DAMAGE,DANGER,DEALER,DEBATE,DECADE,DECENT,DECIDE,DEFEAT,DEFEND,DEFINE,DEGREE,DEMAND,DEPART,DEPEND,DEPLOY,DEPOSIT,DEPUTY,DESERT,DESIGN,DESIRE,DETAIL,DETECT,DEVICE,DIFFER,DINNER,DIRECT,DOCTOR,DOMAIN,DOMINO,DOUBLE,DRIVEN,DRIVER,DURING,EASILY,EFFECT,EFFORT,EITHER,ELDERLY,ELEVEN,EMERGE,EMPIRE,EMPLOY,ENABLE,ENGAGE,ENGINE,ENOUGH,ENSURE,ENTIRE,ENTITY,EQUITY,ESCAPE,ESTATE,ETHNIC,EVOLVE,EXCEPT,EXCESS,EXPAND,EXPECT,EXPERT,EXPORT,EXTEND,EXTENT,FABRIC,FACING,FACTOR,FAILED,FAIRLY,FAMILY,FAMOUS,FATHER,FELLOW,FEMALE,FIGURE,FILTER,FINGER,FINISH,FISCAL,FLIGHT,FLYING,FOLLOW,FORCED,FORGET,FORMAL,FORMAT,FORMER,FOSTER,FOUGHT,FOURTH,FRIEND,FUTURE,GARDEN,GATHER,GENDER,GENTLE,GLOBAL,GOLDEN,GROUND,GROWTH,GUILTY,HAMMER,HANDED,HANDLE,HAPPEN,HARDLY,HEALTH,HEIGHT,HIDDEN,HOLDER,HONEST,HUNGRY,IGNORE,IMPACT,IMPORT,IMPOSE,INCOME,INDEED,INJURY,INSIDE,INTEND,INTENT,INVEST,INVITE,ISLAND,ITSELF,JOINED,JUNIOR,JUSTIN,KIDNEY,LADDER,LAUNCH,LAWSUIT,LAWYER,LEADER,LEAGUE,LEAVES,LEGACY,LENGTH,LESSON,LETTER,LIKELY,LIQUID,LISTEN,LITTLE,LIVELY,LIVING,LOCATE,LONELY,LOSING,LOVELY,MAINLY,MAKING,MANAGE,MANNER,MARGIN,MARKET,MASTER,MATTER,MATURE,MEDIUM,MEMBER,MEMORY,MENTAL,MERELY,METHOD,MIDDLE,MINUTE,MIRROR,MOBILE,MODEST,MODIFY,MODULE,MOMENT,MOSTLY,MOTHER,MOTION,MOVING,MURDER,MUSCLE,MUTUAL,MYSELF,NARROW,NATION,NATIVE,NATURE,NEARBY,NEARLY,NEEDLE,NEPHEW,NEUTRAL,NIGHTS,NOBODY,NORMAL,NOTICE,NOTION,NUMBER,OBJECT,OBTAIN,OFFICE,OFFSET,ONLINE,OPPOSE,OPTION,ORANGE,ORIGIN,OXYGEN,PARENT,PARTLY,PATENT,PATROL,PAYING,PEOPLE,PERIOD,PERMIT,PERSON,PHRASE,PLAYED,PLAYER,PLEASE,POCKET,POETRY,POLICE,POLICY,POSTER,PREFER,PRETTY,PRINCE,PRISON,PROFIT,PROPER,PROVEN,PUBLIC,PURPLE,PURSUE,QUARRY,RAREST,RARELY,RATHER,RATING,READER,REALLY,REASON,RECALL,RECENT,RECORD,REDUCE,REFUSE,REGARD,REGIME,REGION,REJECT,RELATE,RELIEF,REMAIN,REMOTE,REMOVE,REPAIR,REPEAT,REPLY,REPORT,RESCUE,RESORT,RESULT,RETAIL,RETAIN,RETIRE,RETURN,REVEAL,REVIEW,REWARD,RIDING,RISING,ROCKET,RULING,SAFETY,SAMPLE,SCHEME,SCHOOL,SCREEN,SEARCH,SEASON,SECOND,SECRET,SECTOR,SECURE,SEEING,SELECT,SELLER,SENIOR,SERIES,SERVER,SETTLE,SEVERE,SEXUAL,SHADOW,SHAPED,SHARED,SIMPLE,SIMPLY,SINGLE,SISTER,SLIGHT,SLOWLY,SMOOTH,SOCCER,SOCIAL,SOLELY,SOONER,SOURCE,SPEECH,SPIRIT,SPOKEN,SPREAD,SPRING,SQUARE,STABLE,STAFF,STATIC,STATUE,STATUS,STEADY,STOLEN,STRAIN,STREAM,STREET,STRESS,STRICT,STRIKE,STRING,STRIPE,STRONG,STRUCK,STRUNG,STUDIO,STUPID,SUBMIT,SUDDEN,SUFFER,SUMMER,SUMMIT,SUPPLY,SURELY,SURVEY,SWITCH,SYMBOL,SYSTEM,TACKLE,TALENT,TARGET,TAUGHT,TENANT,TENDER,TENNIS,THANKS,THEORY,THIRTY,THOUGH,THREAT,THRIVE,THROAT,THROWN,TICKET,TIMELY,TISSUE,TOWARD,TRAVEL,TREATY,TRYING,TWELVE,TWENTY,UNABLE,UNIQUE,UNITED,UNLESS,UNLIKE,UPDATE,UPLIFT,USEFUL,USERS,VALLEY,VARIED,VENDOR,VERIFY,VERSUS,VICTIM,VIEWER,VIOLET,VIRTUE,VISION,VISUAL,VOLUME,WALKED,WALKER,WEALTH,WEIGHT,WIDELY,WINNER,WINTER,WISDOM,WITHIN,WONDER,WORKER,WRITER,YELLOW";
  const extras7 = "ABILITY,ABSENCE,ACADEMY,ACCOUNT,ACCUSED,ACHIEVE,ACQUIRE,ADDRESS,ADVANCE,ADVERSE,ADVISER,AGAINST,AIRLINE,AIRPORT,ALCOHOL,ALLIANCE,ALREADY,ALTHOUGH,AMAZING,ANCIENT,ANOTHER,ANXIETY,ANXIOUS,ANYBODY,ANYMORE,ANYWAY,APPLIED,ARRANGE,ARRIVAL,ARTICLE,ASSAULT,ASSURED,ATTEMPT,ATTRACT,AUCTION,AVERAGE,BALANCE,BARRIER,BATTERY,BEARING,BEATING,BECAUSE,BEDROOM,BELIEVE,BENEATH,BENEFIT,BESIDES,BETWEEN,BILLION,BINDING,BLOCKED,BROTHER,BROUGHT,BUDGET,BURNING,CABINET,CALIBER,CAPABLE,CAPITAL,CAPTAIN,CAPTION,CAPTURE,CAREFUL,CARRIER,CAUTION,CEILING,CENTRAL,CENTURY,CERTAIN,CHAMBER,CHANNEL,CHAPTER,CHARITY,CHARTER,CHIMNEY,CIRCUIT,CITIZEN,CLASSIC,CLIMATE,CLOSING,CLOTHES,COLLECT,COLLEGE,COMBINE,COMMAND,COMMENT,COMPANY,COMPARE,COMPETE,COMPLEX,CONCEPT,CONCERN,CONCERT,CONDUCT,CONFIRM,CONNECT,CONSENT,CONSIST,CONTACT,CONTAIN,CONTENT,CONTEST,CONTEXT,CONTROL,CONVERT,CORRECT,COUNSEL,COUNTRY,CRYSTAL,CULTURE,CURRENT,DECLINE,DEFAULT,DEFENCE,DEFICIT,DELIVER,DENSITY,DEPOSIT,DESPITE,DESTROY,DEVELOP,DIAMOND,DISCUSS,DISEASE,DISMISS,DISPLAY,DIVERSE,DIVIDED,DRAWING,DRIVING,DYNAMIC,EARLIER,ECONOMY,EDITION,ELDERLY,ELEVATE,ELEVEN,ENGAGED,ENHANCE,ENGLISH,EXAMINE,EXAMPLE,EXCITED,EXECUTE,EXHAUST,EXHIBIT,EXPENSE,EXPLAIN,EXPLORE,EXPRESS,EXTREME,FACTORY,FACULTY,FAILING,FANTASY,FASHION,FEATURE,FEDERAL,FEELING,FICTION,FIFTEEN,FIGHTER,FILLING,FINANCE,FINDING,FISHING,FITNESS,FOREIGN,FOREVER,FORMULA,FORTUNE,FORWARD,FOUNDED,FREEDOM,FURTHER,GALLERY,GENERAL,GENETIC,GENUINE,GIGGLE,GLIMPSE,GRABBED,GRANTED,GRAPHIC,GREATER,GROCERY,HABITAT,HANGING,HARMONY,HEADING,HEALTHY,HEARING,HIGHWAY,HIMSELF,HISTORY,HOLDING,HOLIDAY,HOUSING,HOWEVER,HUNDRED,HUSBAND,IMAGINE,IMPROVE,INCLUDE,INITIAL,INQUIRY,INSIGHT,INSPIRE,INSTALL,INSTANT,INSTEAD,INTENSE,INVOLVE,JEALOUS,JOURNAL,JOURNEY,JUSTICE,KITCHEN,LARGELY,LASTING,LEADING,LEISURE,LIBERAL,LIBRARY,LICENSE,LIMITED,LISTING,LOGICAL,MACHINE,MANAGER,MARRIED,MASSAGE,MASSIVE,MATTERS,MAXIMUM,MEANING,MEASURE,MEDICAL,MEETING,MENTION,MESSAGE,MIDNIGHT,MILEAGE,MILITIA,MILLION,MINERAL,MINIMUM,MISSING,MISSION,MISTAKE,MIXTURE,MORNING,MULTIPLY,MUSICAL,MYSTERY,NATURAL,NEEDFUL,NETWORK,NOTABLE,NOTHING,NOTICED,OBVIOUS,OFFENSE,OFFICER,ONGOING,OPENING,OPINION,OPPOSED,OPTIMAL,OPTIMUM,ORGANIC,OUTCOME,OUTLOOK,OUTSIDE,OVERALL,PACKAGE,PAINFUL,PAINTED,PARKING,PARTIAL,PARTNER,PASSAGE,PASSION,PASSIVE,PATIENT,PATTERN,PAYMENT,PENALTY,PENDING,PERCENT,PERFECT,PERFORM,PERHAPS,PICTURE,PIONEER,PLANNED,PLASTIC,POINTED,POPULAR,PORTION,POVERTY,PRECISE,PREDICT,PREMISE,PREMIUM,PREPARE,PRESENT,PREVENT,PRIMARY,PRINTED,PRIVACY,PRIVATE,PROBLEM,PROCEED,PROCESS,PRODUCE,PRODUCT,PROFILE,PROGRAM,PROJECT,PROMISE,PROMOTE,PROTECT,PROTEST,PROVIDE,PUBLISH,PURPOSE,PURSUIT,PUSHING,QUALIFY,QUALITY,QUICKLY,RAILWAY,READING,REALITY,REALIZE,RECEIPT,RECEIVE,RECOVER,REFLECT,REGARDS,RELATED,RELEASE,REPLACE,REQUEST,REQUIRE,RESERVE,RESPECT,RESPOND,RESTORE,RETIRED,REVEALS,REVENUE,REVERSE,ROUTINE,RUNNING,SATISFY,SCANDAL,SCATTER,SCIENCE,SECTION,SEEKING,SEGMENT,SERIOUS,SERVICE,SERVING,SETTING,SEVENTH,SEVERAL,SHELTER,SILENCE,SILVER,SIMILAR,SITTING,SIXTEEN,SKILLED,SLAVERY,SMOKING,SOCIETY,SOLDIER,SOMEDAY,SOMEHOW,SOMEONE,SPECIAL,SPECIES,SPONSOR,STADIUM,STATION,STATUTE,STAYING,STORAGE,STRANGE,STRETCH,SUBJECT,SUCCEED,SUCCESS,SUGGEST,SUMMARY,SUPPORT,SUPPOSE,SUPREME,SURFACE,SURGERY,SURPLUS,SURVIVE,SUSPECT,SUSTAIN,TALKING,TEACHER,TENSION,TESTIFY,TEXTURE,THEATER,THEREBY,THOUGHT,THROUGH,TONIGHT,TROUBLE,TRUSTED,TRYING,TURNING,TYPICAL,UNIFORM,UNUSUAL,UPGRADE,UTILITY,VARIETY,VARIOUS,VEHICLE,VENDORS,VERSION,VETERAN,VICTORY,VILLAGE,VIRGINIA,VISIBLE,WAITING,WALKING,WARNING,WARRANT,WEARING,WEATHER,WEDDING,WEEKEND,WEIGHTS,WELCOME,WELFARE,WESTERN,WHEREAS,WHETHER,WILLING,WINDOWS,WITHDRAW,WITNESS,WORKING,WRITING,WRITTEN";

  const valid = { 5: new Set(), 6: new Set(), 7: new Set() };
  for (const len of [5, 6, 7]) {
    for (const w of FOODLE_WORDS[len]) valid[len].add(w.w);
    const extras = len === 5 ? extras5 : len === 6 ? extras6 : extras7;
    for (const w of extras.split(",")) {
      const c = w.trim().toUpperCase();
      if (c.length === len) valid[len].add(c);
    }
  }
  return valid;
})();

window.FOODLE_WORDS = FOODLE_WORDS;
window.FOODLE_VALID = FOODLE_VALID;
